the-guild-org/website

- pages/blog/graphql-over-websockets.mdx
Hello 👋 , me again,
[`graphql-ws@v2` had a small breaking change](https://github.com/enisdenjo/graphql-ws/releases/tag/v2.0.0), this PR adjusts the example reflecting that. 😄
> docs: Update graphql-ws server example

- pages/blog/a-new-year-for-schema-stitching.mdx
@Urigo – look right? I've never done one of these.
> blog post: A New Year for Schema Stitching

- pages/about-us.mdx
Hi. This is just a small PR to add the discord invite link to the about us page.
> Fix Discord invite link

- README.md
Just a small PR updating README for the guild website adding instructions on running the website locally, contributing to the blog,
> Updated README for the guild website

- pages/blog/graphql-over-websockets.mdx
Just a quick refresh. 😄 
- Visualise how to unsubscribe from a subscription
- As of [`v4.3.0`](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.3.0) the `execute` and `subscribe` server arguments are optional
- As of [`v4.4.0`](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.4.0) `graphql-ws` ships with built-in [µWebSockets](https://github.com/uNetworking/uWebSockets.js) integration
> `graphql-ws` examples adjustments and showcase µWebSockets

- ui/platform-section.tsx
<https://www.graphql-config.com/introduction> 404
> docs: fix graphql-config documentation link

- .eslintrc.cjs
- pages/_app.tsx
- pages/_document.tsx
- pages/blog.tsx
- public/static/banner.js
- public/static/no-flash.mjs
- ui/recommended-reading-section.tsx
fixes https://github.com/the-guild-org/the-guild-website/issues/589 https://github.com/the-guild-org/the-guild-website/issues/604
> fix flash on initial loading

- pages/_app.tsx
fixes https://github.com/the-guild-org/the-guild-website/issues/606
> remove italics from code font

- next.config.mjs
If somebody wants to talk to us we could just share `the-guild.dev/chat` and it will point to https://go.crisp.chat/chat/embed/?website_id=af9adec5-ddfa-4db9-a4a3-25769daf2fc2
> Introduce /chat

- styles/global.ts
- ui/platform-section.tsx
> fix background color in header

- pages/blog/subscriptions-and-live-queries-real-time-with-graphql.mdx
> add live query video to blog post

- pnpm-lock.yaml
- website/pages/blog/caching-data-with-dataloader.mdx
- website/pages/blog/graphql-codegen-best-practices.mdx
- website/pages/blog/graphql-codegen-hooks-support-react-apollo.mdx
fixes https://github.com/the-guild-org/the-guild-website/issues/824
> fix :::tip

- website/theme.config.tsx
> Use thumbnail instead of image for og:image

- website/pages/index.mdx
- website/theme.config.tsx
Signed-off-by: Tuval Simha <tuval.simha@gmail.com>
> Website: change <title> for SEO research

- packages/website-router/config.ts
Merge after a successful `master` build of https://github.com/B2o5T/graphql-eslint/pull/1377
> Added GraphQL-ESLint website

- website/lib/get-all-articles.ts
- website/pages/blog/announcing-self-hosted-graphql-hive.mdx
- website/pages/blog/caching-data-with-dataloader.mdx
- website/pages/blog/graphql-code-generator-090.mdx
- website/pages/blog/graphql-code-generator.mdx
- website/pages/blog/graphql-config.mdx
- website/pages/blog/graphql-deep-dive-2.mdx
- website/pages/blog/graphql-deep-dive-3.mdx
- website/pages/blog/graphql-deep-dive-4.mdx
- website/pages/blog/graphql-deep-dive-5.mdx
- website/pages/blog/graphql-hive-improvements-in-schema-registry.mdx
- website/pages/blog/graphql-mesh.mdx
- website/pages/blog/graphql-modules-auth.mdx
- website/pages/blog/graphql-modules.mdx
- website/pages/blog/graphql-tools-v7.mdx
- website/pages/blog/graphql-tools-v8.mdx
- website/pages/blog/manage-circular-imports-hell-in-graphql-modules.mdx
- website/pages/blog/meteor-with-webpack-in-2018.mdx
- website/pages/blog/migrating-from-rest.mdx
- website/pages/blog/slack-bot-with-cloudflare.mdx
- website/pages/blog/subscriptions-and-live-queries-real-time-with-graphql.mdx
- website/pages/blog/unleash-the-power-of-fragments-with-graphql-codegen.mdx
Signed-off-by: Tuval Simha <tuval.simha@gmail.com>
> SEO rules: description length

- website/pages/index.mdx
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
> SEO: title change + thumbnail

- website/pages/blog/offline-graphql-the-easy-parts.mdx
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
> SEO: change title to `Flutter GraphQL` keyword

- website/pages/blog/offline-graphql-the-easy-parts.mdx
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
> Fix `title` for Flutter GraphQL blog

- package.json
Reverts the-guild-org/website#1285
> Revert "chore(deps): update pnpm to v8.6.5"

- website/ui/platform-section.tsx
> Align lib logos

- packages/website-helper-worker/package.json
- packages/website-router/package.json
- pnpm-lock.yaml
Reverts the-guild-org/website#1413
> Revert "chore(deps): update dependency wrangler to v3.11.0"

- .github/workflows/helper-worker-deploy.yaml
- .github/workflows/website-router-deploy.yaml
Reverts the-guild-org/website#1348
> Revert "chore(deps): update cloudflare/wrangler-action action to v3"

- packages/website-router/src/banner.ts
- packages/website-router/src/config.ts
Reverts the-guild-org/website#1554
> Revert "enable graphql conf 2024 banner"

- packages/website-router/src/banner.ts
> add utm sources to conf banner

- .github/workflows/ci.yaml
- .github/workflows/helper-worker-deploy.yaml
- .github/workflows/lint.yaml
- .github/workflows/website-router-deploy.yaml
- package.json
> feat: upgrade node to 22

- .github/workflows/ci.yaml
- .github/workflows/helper-worker-deploy.yaml
- website/lib/all-blogs.ts
- website/pages/blog/stellate-acquisition.mdx
- **style: prettier fix**
- **fix lint issues**
- **fix**
- **eslint ignore**
> fix linting issues

- website/pages/blog/nextra-4/index.mdx
Hi there, when I tried to update the Nextra v4 documentation, I thought the migration guide could also be refined for clarity. Feel free to close this if it’s unnecessary or edit it directly if it’s unsuitable.
> Improve clarity in the Nextra v4 post

- .prettierrc.cjs
- packages/website-router/src/routing.ts
Fixes https://github.com/the-guild-org/website/issues/1851
> Add google analytics to 404 pages so they can be tracked with additional details

- website/ui/hero/index.tsx
> Change Mesh tagline and switch up Router and Gateway
